liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

        # configure resolvers
    resolvers :

        # setup the default resolver
        default :

            # use the default web path
            web_path : ~

    filter_sets:
        cache: ~

        # Nom du filtre
        thumbnail:

            # Ajuster la qualité de l'image
            quality: 85
            # Listes des différentes transformations
            filters:
                # Création d'une vignette
                thumbnail: { size: [600, 350], mode: outbound }
        
        # Autres filtres...
        vignette:
            quality: 85
            filters:
                thumbnail: { size: [200, 100], mode: outbound }
                


        details:
            quality: 85
            filters:
                thumbnail: { size: [425, 375], mode: 'outbound' }
                background: { size: [600, 450], position: center, color: '#000000' }
              
