liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        # Nom du filtre
        thumbnail:

            # Ajuster la qualité de l'image
            quality: 85
            # Listes des différentes transformations
            filters:
                # Création d'une vignette
                thumbnail: { size: [600, 350], mode: outbound }
        
        # Autres filtres...
        vignette:
            quality: 85
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
                background: { size: [425, 375], position: center, color: '#000000' }


        details:
            quality: 85
            filters:
                thumbnail: { size: [600, 350], mode: 'outbound' }
                background: { size: [425, 375], position: center, color: '#000000' }