twig:
    default_path: '%kernel.project_dir%/templates'

    # Pour avoir une jolie vue sur le formulaire avec bootstrap
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
