vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       articles:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
